### ISSUE TITLE
Split out `str_utils` module from Ropey?

### ISSUE THREAD

**Issue by cessen** [josephg/jumprope-rs#1]
Hi there!  It's awesome to see that you're working on this again, and that you've made it so blazing fast!

I noticed that you have a dependency on [Ropey](https://github.com/cessen/ropey/), apparently just for a couple of functions in Ropey's `str_utils` module.  I'm wondering if it would make sense for me to split off `str_utils` into a separate crate, so you don't have to depend on all of Ropey just for those functions.  Would that be useful to you?

(As a bonus, I'm pretty sure I can make it zero-dependencies and `no_std` if I do that.)

**Comment by josephg** [comment]
Oh, I somehow missed this!

I'd love for str_utils to be a separate crate. I was just in the process of inlining some of those methods here, but using a shared version would be much cleaner.

**Comment by cessen** [comment]
Awesome!  I'll work on splitting that out soon, then.

**Comment by cessen** [comment]
Done: https://crates.io/crates/str_indices

**Comment by josephg** [comment]
Awesome! Thankyou 🔥
